### ISSUE TITLE
SDK该更新了？涉及写入权限全线Insufficient app permissions

### ISSUE THREAD

**Issue by kn007** [xiaosier/libweibo#19]
SDK中的demo也是一样。
CODE: 10014

**Comment by ltreer** [comment]
我的也是，是什么原因

**Comment by xiaosier** [comment]
请从open.weibo.com 申请接口权限。

**Comment by kn007** [comment]
@xiaosier 已经在几年前就申请了。
而且demo调用的是基础写入，也不行，这不是在搞笑吗？

**Comment by kn007** [comment]
口气有点不好。见谅。
现在无论是普通还是高级写入都是不行。
按道理demo是普通写入，更应该没问题才对。
主要是都已经在线上跑了几年了，突然不行，很无语。

**Comment by ltreer** [comment]
我这里也是使用很久了，突然就不行了@xiaosier  ，要申请什么权限

**Comment by Cp0204** [comment]
微博开放平台改了接口，没有微博写入接口了，改成了分享接口：
http://open.weibo.com/wiki/2/statuses/share



`        /**
         * 第三方分享链接到微博
         *
         * 发表图片微博消息。目前上传图片大小限制为<5M。 
         * <br />对应API：{@link http://open.weibo.com/wiki/2/statuses/share statuses/share}
         * 
         * @access public
         * @param string $status 用户分享到微博的文本内容，必须做URLencode，内容不超过140个汉字，文本中不能包含“#话题词#”，同时文本中必须包含至少一个第三方分享到微博的网页URL。
         * @param string $pic_path 要发布的图片路径, 支持url。[只支持png/jpg/gif三种格式, 增加格式请修改get_image_mime方法]
         * @return array
         */
        function share( $status, $pic_path = NULL )
        {
            $multi = false;
            $params = array();
            $params['status'] = $status;
            if ($pic_path) {
                $params['pic'] = '@'.$pic_path;
                $multi = true;
            }
            return $this->oauth->post( 'statuses/share', $params, $multi );
        }
`

自己加，并且微博文字里要包含安全域名下的一个URL~ 天煞的

**Comment by kn007** [comment]
再次说明官方SDK的不作为。

**Comment by kn007** [comment]
已改变线上代码后解决。再次感谢@Cp0204 。
目前使用自制的函数正常使用了，SDK有点肿说实在的，不愿意用。但还是希望@xiaosier 能更新一下，毕竟过期函数了。谢谢。

**Comment by kn007** [comment]
@Cp0204 请教下兄弟，是在哪看到微博开放平台改了接口，新接口文档目录有么？谢谢

**Comment by xiaosier** [comment]
已经更新了，该SDK由新浪云维护，不是微博自己维护的，和开放平台沟通后，他们给出的答复是三月份已经通知调整，http://weibo.com/1904178193/EC38wwLUf?from=page_1006061904178193_profile&wvr=6&mod=weibotime&type=comment 

另外近期也发送了邮件给开发者们，建议大家使用客户端SDK写入，官方申明在这里：http://open.weibo.com/blog/%E3%80%90%E5%B9%B3%E5%8F%B0%E5%85%AC%E5%91%8A%E3%80%91%E5%BE%AE%E5%8D%9A%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0%E5%88%86%E4%BA%AB%E5%88%B0%E5%BE%AE%E5%8D%9A%E6%8E%A5%E5%8F%A3%E5%8D%87%E7%BA%A7%E5%85%AC

感谢各位反馈。

**Comment by kn007** [comment]
好的，谢谢@xiaosier ，可惜我没收到邮件。。
不过按这么说，新浪云没对SDK更新，也是非常可惜的。

**Comment by kn007** [comment]
还有官方博客的链接有点意思，中文就算了，还缺字。。。
